[project]
name = "mem-first-web-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=1.0.8",
    "openai>=2.21.0",
]
